language: java

jdk:
 - oraclejdk8

script:
 - mvn clean
 - mvn package

after_success:
 - mvn install archetype:update-local-catalog
 - mkdir test && cd test
 - mvn archetype:generate -B -DarchetypeGroupId=scala -DarchetypeArtifactId=finatra-archetype -DarchetypeVersion=18.1.0 -DgroupId=company -DartifactId=projectx -Dpackage=company.projectx -DarchetypeCatalog=local
 - cd projectx && mvn package